services:
  app:
    build:
      context: .
      target: runtime
      args:
        DATABASE_URL: ${DATABASE_URL}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NBU_BANKS_URL: ${NBU_BANKS_URL}
    image: payment_app:local
    pull_policy: never
    command: ["pnpm", "start"]
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      - logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  cron: # фоновые задания
    image: payment_app:local
    pull_policy: never
    command: ["node", "dist/scripts/cronJob.js"]
    env_file: .env
    depends_on:
      - app
    volumes:
      - logs:/app/logs
    restart: on-failure

volumes:
  logs: 
